language: python
python:
  - "2.7"
env:
  global:
    - EEA_PASSWORD_RESET=https://www.example.com/password-reset
install:
  - pip install -r requirements-dev.txt --trusted-host eggshop.eaudeweb.ro
  - pip install pytest-cov==1.8.1 coverage==3.7.1 coveralls==0.5
before_script:
  - cp settings.py.example instance/test_settings.py
  - mysql -e 'create database art12;'
script:  py.test --cov=art12 testsuite
after_success: coveralls
notifications:
  email:
      recipients:
            - purepython@eaudeweb.ro
