version: '2'

services:

  art12-app:
    # image: eeacms/art12-viewer:latest
    build:
      context: .
    container_name: art12.app
    environment:
    - COLLECT_STATIC=yes
    - MIGRATE=yes
    - TZ=Europe/Copenhagen
    ports:
    - "5000:5000"
    depends_on:
    - db
    env_file:
    - docker/art12.env
    volumes:
    - .:/var/local/art12

    entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    # command: ["runserver", "-t", "0.0.0.0", "-p", "5000"]

  db:
    image: postgres:13
    container_name: art12.db
    ports:
    - '5431:5432'
    env_file:
    - docker/art12.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - pg_data:/var/lib/postgresql/data
    - ./docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  postfix:
    image: eaudeweb/mailtrap:2.0
    container_name: art12.postfix
    environment:
      TZ: Europe/Copenhagen
    ports:
    - 80:80

volumes:
  pg_data:
    driver: local
