version: '2'

services:

  art12-app:
    image: eeacms/art12-viewer:latest
    container_name: art12.app
    environment:
    - COLLECT_STATIC=yes
    - MIGRATE=yes
    - TZ=Europe/Copenhagen
    ports:
    - "5000:5000"
    depends_on:
    - mysql
    env_file:
    - docker/art12.env
    volumes:
    - .:/var/local/art12

    entrypoint: ["/usr/bin/tail", "-f", "/dev/null"]
    # command: ["runserver", "-t", "0.0.0.0", "-p", "5000"]

  mysql:
    image: mysql:5.6
    container_name: art12.mysql
    env_file:
    - docker/art12.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - mysqldata:/var/lib/mysql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  postfix:
    image: eaudeweb/mailtrap:2.0
    container_name: art12.postfix
    environment:
      TZ: Europe/Copenhagen
    ports:
    - 80:80

volumes:
  mysqldata:
    driver: local
