version: '2'

services:

  art12:
    image: eeacms/art12-viewer:latest
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - mysql
    env_file:
    - ../art12.env
    environment:
      TZ: Europe/Copenhagen

  mysql:
    image: mysql:latest
    labels:
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    env_file:
    - ../art12.env
    environment:
      TZ: Europe/Copenhagen
    volumes:
    - mysqldata:/var/lib/mysql
    command: "--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"

  rsync-server:
    image: eeacms/rsync
    labels:
      io.rancher.container.pull_image: always
      io.rancher.scheduler.affinity:host_label_ne: reserved=yes
    depends_on:
    - art12
    - mysql
    ports:
    - "2222:22/tcp"
    command:
    - server
    env_file:
    - ../rsync.key
    environment:
      TZ: Europe/Copenhagen
    tty: true
    stdin_open: true
    volumes:
    - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
    driver: local
