"""add Config table

Revision ID: 31ed56cad45a
Revises: 3c8e31fa45ca
Create Date: 2014-10-06 12:22:07.478672

"""

# revision identifiers, used by Alembic.
revision = '31ed56cad45a'
down_revision = '3c8e31fa45ca'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('default_dataset_id', sa.Integer(), nullable=True),
    sa.Column('species_map_url', sa.String(length=255), nullable=True),
    sa.Column('sensitive_species_map_url', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.alter_column(u'datasets', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
    op.create_unique_constraint(None, 'datasets', ['id'])
    op.create_index(op.f('ix_etc_data_birds_group'), 'etc_data_birds', ['group'], unique=False)
    op.alter_column(u'lu_birds_name', 'ext_dataset_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column(u'lu_birds_name', 'speciescode',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)
    ### end Alembic commands ###

    op.execute("INSERT INTO `art12`.`config` (`id`, `default_dataset_id`) "
               "VALUES ('1', '1');")


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'lu_birds_name', 'speciescode',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
    op.alter_column(u'lu_birds_name', 'ext_dataset_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_index(op.f('ix_etc_data_birds_group'), table_name='etc_data_birds')
    op.drop_constraint(None, 'datasets')
    op.alter_column(u'datasets', 'name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
    op.drop_table('config')
    ### end Alembic commands ###
