from factory.alchemy import SQLAlchemyModelFactory

from art12 import models


class DatasetFactory(SQLAlchemyModelFactory):
    class Meta:
        model = models.Dataset
        sqlalchemy_session = models.db.session

    id = 1
    name = "import-from-2006"


class LuDataBirdFactory(SQLAlchemyModelFactory):
    class Meta:
        model = models.LuDataBird
        sqlalchemy_session = models.db.session

    dataset_id = 1
    speciescode = "1111"
    speciesname = "Species name 1"


class EtcDataBirdFactory(SQLAlchemyModelFactory):
    class Meta:
        model = models.EtcDataBird
        sqlalchemy_session = models.db.session

    country = "AT"
    country_isocode = "AUT"
    delivery = 1
    envelope = "envelope"
    filename = "filename"
    reported_name = "reported_name"
    group = "group"
    family = "family"
    annex = "annex"
    priority = "1"
    redlist = 0
    euringcode = "euringcode"
    code = "code"
    speciescode = "1111"
    speciesname = "Species name 1"
    species_name_different = 0
    subspecies_name = "subspecies_name"
    eunis_species_code = 1
    alternative_speciesname = "alternative_speciesname"
    common_speciesname = "common_speciesname"
    valid_speciesname = "valid_speciesname"
    n2000_species_code = 1
    assessment_speciescode = "1111"
    assessment_speciesname = "assessment_speciesname"
    assessment_speciesname_changed = 0
    grouped_assesment = 0
    species_type = "stype"
    species_type_asses = 0
    range_surface_area_bs = 2.0
    range_change_reason_bs = "range_change_reason_bs"
    percentage_range_surface_area_bs = 3.0
    range_additional_info_record_bs = "1"
    range_additional_info_bs = "range_additional_info_bs"
    range_trend_period_bs = "r"
    range_trend_bs = "r"
    range_trend_magnitude_min_bs = 4.0
    range_trend_magnitude_max_bs = 5.0
    range_trend_long_period_bs = "r"
    range_trend_long_bs = "r"
    range_trend_long_magnitude_min_bs = 6.0
    range_trend_long_magnitude_max_bs = 7.0
    range_trend_additional_info_record_bs = "1"
    range_trend_additional_info_bs = "range_trend_additional_info_bs"
    range_yearly_magnitude_bs = 8.0
    complementary_favourable_range_op_bs = "cf"
    complementary_favourable_range_bs = 9.0
    population_minimum_size_bs = "35000"
    percentage_population_minimum_size_bs = 10.0
    population_maximum_size_bs = "10000"
    percentage_population_maximum_size_bs = 11.0
    population_size_bs = "population_size_bs"
    population_size_method_bs = "population_size_method_bs"
    filled_population_bs = "fp"
    population_size_unit_bs = "population_size_unit_bs"
    population_units_agreed_bs = "population_units_agreed_bs"
    population_units_other_bs = "population_units_other_bs"
    population_estimateType_bs = "population_estimateType_bs"
    population_change_reason_bs = "population_change_reason_bs"
    number_of_different_population_units_bs = 12
    different_population_percentage_bs = 13
    percentage_population_mean_size_bs = "ppmsb"
    population_additional_info_record_bs = "1"
    population_additional_info_bs = "population_additional_info_bs"
    population_trend_period_bs = "population_trend_period_bs"
    population_trend_bs = "ptb"
    population_trend_magnitude_min_bs = 14.0
    population_trend_magnitude_max_bs = 15.0
    population_trend_magnitude_bs = "population_trend_magnitude_bs"
    population_trend_long_period_bs = "population_trend_long_period_bs"
    population_trend_long_bs = "ptb"
    population_trend_long_magnitude_min_bs = 16.0
    population_trend_long_magnitude_max_bs = 17.0
    population_trend_long_magnitude_bs = "population_trend_long_magnitude_bs"
    population_trend_additional_info_record_bs = "1"
    population_trend_additional_info_bs = "population_trend_additional_info_bs"
    population_yearly_magnitude_bs = 18.0
    complementary_favourable_population_op_bs = "cf"
    complementary_favourable_population_bs = 19.0
    filled_complementary_favourable_population_bs = "fc"
    distribution_surface_area_bs = "distribution_surface_area_bs"
    distribution_surface_area_method_bs = "distribution_surface_area_method_bs"
    distribution_additional_info_record_bs = "1"
    distribution_additional_info_bs = "distribution_additional_info_bs"
    percentage_distribution_surface_area_bs = "percentage_distribution_surface_area_bs"
    distribution_trend_period_bs = "distribution_trend_period_bs"
    distribution_trend_bs = "dtb"
    distribution_trend_magnitude_min_bs = 20.0
    distribution_trend_magnitude_max_bs = 21.0
    distribution_trend_magnitude_bs = "distribution_trend_magnitude_bs"
    distribution_trend_long_period_bs = "distribution_trend_long_period_bs"
    distribution_trend_long_bs = "dtl"
    distribution_trend_long_magnitude_min_bs = 22.0
    distribution_trend_long_magnitude_max_bs = 23.0
    distribution_trend_long_magnitude_bs = "distribution_trend_long_magnitude_bs"
    distribution_trend_additional_info_record_bs = "1"
    distribution_trend_additional_info_bs = "distribution_trend_additional_info_bs"
    population_minimum_size_ws = "10000"
    percentage_population_minimum_size_ws = 24.0
    population_maximum_size_ws = "10000"
    percentage_population_maximum_size_ws = 25.0
    population_size_ws = "population_size_ws"
    population_size_method_ws = "population_size_method_ws"
    filled_population_ws = "fp"
    population_size_unit_ws = "population_size_unit_ws"
    population_units_agreed_ws = "puaw"
    population_units_other_ws = "puow"
    population_estimateType_ws = "population_estimateType_ws"
    population_change_reason_ws = "population_change_reason_ws"
    number_of_different_population_units_ws = 26
    different_population_percentage_ws = 27
    percentage_population_mean_size_ws = "ppmsw"
    population_additional_info_record_ws = "1"
    population_additional_info_ws = "population_additional_info_ws"
    population_trend_period_ws = "ptp"
    population_trend_ws = "ptw"
    population_trend_magnitude_min_ws = 28.0
    population_trend_magnitude_max_ws = 29.0
    population_trend_magnitude_ws = "population_trend_magnitude_ws"
    population_trend_long_period_ws = "population_trend_long_period_ws"
    population_trend_long_ws = "ptl"
    population_trend_long_magnitude_min_ws = 30.0
    population_trend_long_magnitude_max_ws = 31.0
    population_trend_long_magnitude_ws = "population_trend_long_magnitude_ws"
    population_trend_additional_info_record_ws = "1"
    population_trend_additional_info_ws = "population_trend_additional_info_ws"
    status_ws = "status_ws"
    presence_bs = "presence_bs"
    presence_ws = "presence_ws"
    future_prospects = "abcd"
    conclusion_range_bs = "abcd"
    conclusion_population_bs = "abcd"
    conclusion_population_ws = "abcd"
    conclusion_future = "abcd"
    conclusion_assessment = "abcd"
    conclusion_assessment_trend = "ab"
    conclusion_assessment_prev = "abcd"
    conclusion_assessment_change = "ab"
    range_quality_bs = "rqb"
    range_trend_quality_bs = "rtqb"
    range_trend_long_quality_bs = "rtlqb"
    population_quality_bs = "pqb"
    population_trend_quality_bs = "ptqb"
    population_trend_long_quality_bs = "ptlqb"
    population_quality_ws = "pqw"
    population_trend_quality_ws = "ptqw"
    population_trend_long_quality_ws = "ptlqw"
    further_information = "further_information"
    further_information_english = "further_information_english"
    range_grid_area = 32.0
    percentage_range_grid_area = 33.0
    distribution_grid_area = "dga"
    percentage_distribution_grid_area = "pdga"
    use_for_statistics = "use_for_statistics"
    dataset_id = 1


class EtcBirdsEuFactory(SQLAlchemyModelFactory):
    class Meta:
        model = models.EtcBirdsEu
        sqlalchemy_session = models.db.session

    speciescode = "1111"
    speciesname = "Species name 1"
    reported_name = "reported_name"
    speciesname_subpopulation = "speciesname_subpopulation"
    assessment_speciescode = "1111"
    assessment_speciesname = "assessment_speciesname"
    assessment_subpopulation = "assessment_subpopulation"
    euringcode = "euringcode"
    non_native = "non_native"
    br_range_surface_area = "brsa"
    br_range_surface_area_downrounded = "brsad"
    br_range_trend = "brt"
    br_range_trend_long = "brtl"
    br_population_size = "bps"
    br_distribution_surface_area = 34
    br_distribution_trend = "bdt"
    br_distribution_trend_long = "bdl"
    br_population_minimum_size = 35.0
    br_population_minimum_size_downrounded = 36.0
    br_population_maximum_size = 37.0
    br_population_maximum_size_uprounded = 38.0
    br_population_size_unit = "bpsu"
    br_population_trend = "bpt"
    br_population_trend_long = "bptl"
    br_conclusion_status_label = "bcsl"
    br_contribution_target1 = "bct1"
    br_red_list_cat = "brlc"
    wi_population_size = "wps"
    wi_population_minimum_size = 39.0
    wi_population_minimum_size_downrounded = 40.0
    wi_population_maximum_size = 41.0
    wi_population_maximum_size_uprounded = 42.0
    wi_population_size_unit = "wpsu"
    wi_population_trend = "wpt"
    wi_population_trend_long = "wptl"
    wi_conclusion_status_label = "wcsl"
    wi_contribution_target1 = "wct1"
    wi_red_list_cat = "wrlc"
    conclusion_status_label = "csl"
    conclusion_status_improving = "csi"
    conclusion_status_br_wi = "csbw"
    conclusion_status_level1_record = "csl1r"
    conclusion_status_level1 = "csl1"
    conclusion_status_level2_record = "csl2r"
    conclusion_status_level2 = "csl2"
    conclusion_population_size_unit = "cpsu"
    conclusion_population_minimum_size = 43.0
    conclusion_population_minimum_size_downrounded = 44.0
    conclusion_population_maximum_size = 45.0
    conclusion_population_maximum_size_uprounded = 46.0
    conclusion_population_trend = "cpt"
    conclusion_population_trend_long = "cptl"
    contribution_target1 = "ct1"
    contribution_target1_label = "ctl"
    user = "user"
    last_update = "last_update"
    deleted_record = 0
    decision = "decision"
    user_decision = "user_decision"
    last_update_decision = "last_update_decision"
    dataset_id = 1
    conclusion_status_label_prev = "cslp"
    conclusion_status_br_wi_prev = "csbw"
    additional_record = 1
    red_list_cat_prev = "rlcp"
